include_guard(GLOBAL)

set(LARGETREE_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB LARGETREE_SOURCES
	${LARGETREE_DIR}/src/*.hpp
	${LARGETREE_DIR}/src/*.cpp)

include("${LARGETREE_DIR}/src/rxtools/RxTools.cmake")

set(LARGETREE_EXTERNAL_INCLUDES
	${RXTOOLS_INCLUDES}
	)

set(LARGETREE_EXTERNAL_LINKS
	${RXTOOLS_LINKS}
	)

set(LARGETREE_INCLUDES
	${LARGETREE_EXTERNAL_INCLUDES}
	${LARGETREE_DIR}/src
	)
set(LARGETREE_LINKS
	${LARGETREE_EXTERNAL_LINKS}
	largetree
	)
